explore_scotland/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path
from django.urls import include
from explore_scotland_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('', include('explore_scotland_app.urls')),
    path('', include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

explore_scotland_app/urls.py
from django.urls import path
from explore_scotland_app import views

app_name = 'explore_scotland_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('edit-profile/', views.edit_profile, name='edit_profile'),
    path('delete-account/', views.delete_user, name='delete_user'),
    path('upload-photo/', views.upload_photo, name='upload_photo'),
    path('delete-photo/<int:photo_id>', views.delete_photo, name='delete_photo'),
    path('get-all-photos/<int:count>', views.get_all_photos, name='get_all_photos'),
    path('get-photos-from-days-ago/<int:days>', views.get_photos_from_days_ago, name='get_photos_from_days_ago'),
    path('search-photos/', views.search_photos, name='search_photos'),
    path('picture-page/<int:photo_id>', views.picture_details, name='picture_details'),
    path('picture-page/', views.picture_details, name='picture_details_without_key'),
    path('post-comment/<int:photo_id>', views.post_comment, name='post_comment'),
    path('like-photo/<int:photo_id>', views.like_photo, name='like_photo'),
    path('edit-photo/<int:photo_id>', views.edit_photo, name='edit_photo'),
    path('photo-board/<slug:board_type>', views.photo_board, name='photo_board'),
    path('profile/', views.profile, name='profile'),
    path('about/', views.about, name='about'),
    
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

explore_scotland_app/models.py
from django.db import models

from django.core.exceptions import ValidationError

from django.contrib.auth.models import User

from PIL import Image

from django.core.files.base import ContentFile

class UserProfile(models.Model):
	# user profile to extend user attributes
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
	picture = models.ImageField(upload_to="", null=True, blank=True)
	
	def __str__(self):
		return self.user.username
		
class Photo(models.Model):
	# represents a photo
	LANDSCAPE = 'LS'
	ARCHITECTURE = 'AC'
	PEOPLE = 'PP'

	CATEGORY_CHOICES = [
		(LANDSCAPE, 'Landscape'),
		(ARCHITECTURE, 'Architecture'),
		(PEOPLE, 'People'),
	]
    
	owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="photos_uploaded")
	description = models.TextField(max_length=256)
	date_added = models.DateField(auto_now_add=True)
	categories = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=LANDSCAPE)
	tags = models.CharField(max_length=256, null=True, blank=True) #add choice
	likes = models.ManyToManyField(UserProfile, related_name="photos_liked")
	picture = models.ImageField(upload_to="")
	
	# order by date descending
	class Meta:
		ordering = ('-date_added',)
	
	def __str__(self):
		return self.owner.user.username + " photo."
		
# 	def save(self, *args, **kwargs):
#		# cuts the image to a square
# 		super().save()
# 		img = Image.open(self.picture.path)
# 		width, height = img.size  # Get dimensions
# 
# 		# check which one is smaller
# 		if height < width:
# 			# make square by cutting off equal amounts left and right
# 			left = (width - height) / 2
# 			right = (width + height) / 2
# 			top = 0
# 			bottom = height
# 			img = img.crop((left, top, right, bottom))
# 
# 		elif width < height:
# 			# make square by cutting off bottom
# 			left = 0
# 			right = width
# 			top = 0
# 			bottom = width
# 			img = img.crop((left, top, right, bottom))
# 
# 		img.save(self.picture.path)
		
class Comment(models.Model):
	# represents a comment
	owner = models.ForeignKey(UserProfile, on_delete=models.CASCADE, related_name="comment_posted")
	content = models.TextField(max_length=256)
	photo = models.ForeignKey(Photo, on_delete=models.CASCADE, related_name="photo_comments", null=True, blank=True)
	comment = models.ForeignKey("self", on_delete=models.CASCADE, related_name="comment_comments", null=True, blank=True)
	date_added = models.DateField(auto_now_add=True)
	
	# upon saving, check that both the comment field and photo are not empty
	def save(self):
		super().save()
		if self.photo is None and self.comment is None:
			raise ValidationError('Comments must be linked to either a photo or a comment.')
	
	def __str__(self):
		if self.photo is not None:
			return self.owner.user.username + " comment on " + self.photo.__str__()
		else:
			return self.owner.user.username + " comment on " + self.comment.__str__()

explore_scotland_app/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from explore_scotland_app.models import UserProfile, Photo, Comment

class UserForm(forms.ModelForm):
	# user form for signup
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)
        help_texts = {
			'username': '',
		}

class UserProfileForm(forms.ModelForm):
	# user profile form for getting user's profile picture
    class Meta:
        model = UserProfile
        fields = ('picture',)
        
class UserFormWithoutPassword(UserForm):
	# user form without password to edit details
    def __init__(self, *args, **kwargs):
        super(UserFormWithoutPassword, self).__init__(*args, **kwargs)
        self.fields.pop('password')
        
class PhotoForm(forms.ModelForm):
	# photo form to upload photo
	class Meta:
		model = Photo
		fields = ('picture', 'description', 'categories', 'tags')
		
	def __init__(self, *args, **kwargs):
		super(PhotoForm, self).__init__(*args, **kwargs)
		# add placeholder to form field
		self.fields['tags'].widget.attrs['placeholder'] = 'Separate by space'
		
class CommentForm(forms.ModelForm):
	# comment form to post comment
	class Meta:
		model = Comment
		fields = ('content',)
		labels = {
			'content': ''
		}
		
class PhotoFormWithoutPhoto(PhotoForm):
	# photo form without picture to edit photo details
	def __init__(self, *args, **kwargs):
		super(PhotoFormWithoutPhoto, self).__init__(*args, **kwargs)
		self.fields.pop('picture')

explore_scotland_app/views.py
from django.shortcuts import render

from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from explore_scotland_app.forms import UserForm, UserProfileForm, UserFormWithoutPassword, PhotoForm, CommentForm, PhotoFormWithoutPhoto
from explore_scotland_app.models import UserProfile, Photo, Comment
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime

from django.core.serializers import serialize
import datetime

from django.db.models import Count, Q
import re

from django.contrib import messages

def pop_url(request_meta):
	try:
		return redirect(request_meta.get('HTTP_REFERER'))
	except:
		pass

# render the homepage (index.html)
def index(request):
	return render(request, 'explore_scotland_app/index.html')

# render the homepage (index.html)
def register(request):
	# If it's a HTTP POST, we're interested in processing form data.
	if request.method == 'POST':
		# Attempt to grab information from the raw form information.
		# Note that we make use of both UserForm and UserProfileForm.
		user_form = UserForm(request.POST)
		profile_form = UserProfileForm(request.POST, request.FILES)

		# If the two forms are valid...
		if user_form.is_valid() and profile_form.is_valid():
			# Save the user's form data to the database.
			user = user_form.save()

			# Now we hash the password with the set_password method.
			# Once hashed, we can update the user object.
			user.set_password(user.password)
			user.save()

			# Now sort out the UserProfile instance.
			# Since we need to set the user attribute ourselves,
			# we set commit=False. This delays saving the model
			# until we're ready to avoid integrity problems.
			profile = profile_form.save(commit=False)
			profile.user = user

			# Did the user provide a profile picture?
			# If so, we need to get it from the input form and
			#put it in the UserProfile model.
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']

			# Now we save the UserProfile model instance.
			profile.save()
			
			login(request, user, backend='django.contrib.auth.backends.ModelBackend')
			
			return redirect('explore_scotland_app:index')
	else:
		# Not a HTTP POST, so we render our form using two ModelForm instances.
		# These forms will be blank, ready for user input.
		user_form = UserForm()
		profile_form = UserProfileForm()

	# Render the template depending on the context.
	return render(request,'explore_scotland_app/register.html',context = {'user_form': user_form, 'profile_form': profile_form})

def user_login(request):
	# If the request is a HTTP POST, try to pull out the relevant information.
	if request.method == 'POST':
		# Gather the username and password provided by the user.
		# This information is obtained from the login form.
		# We use request.POST.get('<variable>') as opposed
		# to request.POST['<variable>'], because the
		# request.POST.get('<variable>') returns None if the
		# value does not exist, while request.POST['<variable>']
		# will raise a KeyError exception.
		username = request.POST.get('username')
		password = request.POST.get('password')
		# Use Django's machinery to attempt to see if the username/password
		# combination is valid - a User object is returned if it is.
		user = authenticate(username=username, password=password)
		# If we have a User object, the details are correct.
		# If None (Python's way of representing the absence of a value), no user
		# with matching credentials was found.
		if user:
			# Is the account active? It could have been disabled.
			if user.is_active:
				# If the account is valid and active, we can log the user in.
				# We'll send the user back to the homepage.
				login(request, user)
				return redirect(reverse('explore_scotland_app:index'))
			else:
				# An inactive account was used - no logging in!
				messages.info(request, 'Your Explore Scotland account is disabled.')
				pop_url(request.META)
				return redirect(reverse('explore_scotland_app:login'))
		else:
			# Bad login details were provided. So we can't log the user in.
			messages.info(request, 'Invalid login details supplied.')
			pop_url(request.META)
			return redirect(reverse('explore_scotland_app:login'))
	# The request is not a HTTP POST, so display the login form.
	# This scenario would most likely be a HTTP GET.
	else:
		# No context variables to pass to the template system, hence the
		# blank dictionary object...
		return render(request, 'explore_scotland_app/login.html')

@login_required
def user_logout(request):
	# Since we know the user is logged in, we can now just log them out.
	logout(request)
	# Take the user back to the homepage.
	return redirect(reverse('explore_scotland_app:index'))

@login_required
def edit_profile(request):
	# If the request is a HTTP POST, try to pull out the relevant information.
	if request.method == 'POST':
		user_form = UserFormWithoutPassword(request.POST, instance = request.user)
		profile_form = UserProfileForm(request.POST, request.FILES, instance = request.user.profile)

		# If the two forms are valid...
		if user_form.is_valid() and profile_form.is_valid():
			# Save the user's form data to the database.
			user = user_form.save()

			# Now sort out the UserProfile instance.
			# Since we need to set the user attribute ourselves,
			# we set commit=False. This delays saving the model
			# until we're ready to avoid integrity problems.
			profile = profile_form.save(commit=False)
			profile.user = user

			# Did the user provide a profile picture?
			# If so, we need to get it from the input form and
			#put it in the UserProfile model.
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']

			# Now we save the UserProfile model instance.
			profile.save()

			# Update our variable to indicate that the template
			# registration was successful.
			messages.info(request, 'Update successful.')
			return redirect(reverse('explore_scotland_app:index'))
			
	user_form = UserFormWithoutPassword(instance = request.user)
	profile_form = UserProfileForm(instance = request.user.profile)
	ctx = {
		'user_form': user_form,
		'profile_form': profile_form
	}
	return render(request, 'explore_scotland_app/edit-profile.html', ctx)

# delete a user
@login_required
def delete_user(request):
	# check if teh user exists first
	try:
		request.user.delete()
	except:
		messages.info(request, 'Unable to delete account.')
		pop_url(request.META)
		return redirect(reverse('explore_scotland_app:index'))

	# return to the homepage, if deletion succeeds or fails
	return redirect(reverse('explore_scotland_app:index'))
	
@login_required
def upload_photo(request):
	# If the request is a HTTP POST, try to pull out the relevant information.
	if request.method == 'POST':
		photo_form = PhotoForm(request.POST, request.FILES)

		# If the form is valid...
		if photo_form.is_valid():

			photo = photo_form.save(commit=False)
			photo.owner = request.user.profile

			photo.save()

			# Update our variable to indicate that the template
			# registration was successful.
			ctx = {
				'successful': True,
			}
			return redirect(reverse('explore_scotland_app:profile'))
			
	photo_form = PhotoForm()
	ctx = {
		'photo_form': photo_form,
	}
	return render(request, 'explore_scotland_app/upload-photo.html', ctx)

# delete a photo
@login_required
def delete_photo(request, photo_id):
	# check if the photo exists first
	try:
		photo = Photo.objects.get(pk=photo_id)
	except Photo.DoesNotExist:
		messages.info(request, 'You tried to delete a photo that does not exist.')
		pop_url(request.META)
		return redirect(reverse('explore_scotland_app:profile'))
	# check if the photois from the logged in user
	if photo.owner == request.user.profile:
		photo.delete()
	else:
		messages.info(request, 'You tried to delete a photo you do not own.')
		pop_url(request.META)
		return redirect(reverse('explore_scotland_app:profile'))
	# return to the account profile page
	return redirect(reverse('explore_scotland_app:profile'))
# get all photos
def get_all_photos(request, count):
	photos = serialize('json', Photo.objects.all().annotate(q_count=Count('likes')).order_by('-q_count')[:count])
	return JsonResponse(photos, safe=False)

# get photos from a time period past
def get_photos_from_days_ago(request, days):
	time = datetime.datetime.now() - datetime.timedelta(days = days)
	photos = serialize('json', Photo.objects.filter(date_added__gte=time).annotate(q_count=Count('likes')).order_by('-q_count')[:10])
	return JsonResponse(photos, safe=False)

# Search for a photo
def search_photos(request):
	if request.method == 'GET':
		# Get the search parameters for teh photo
		query_string = request.GET.get("keyword", '')
		sorted_by = request.GET.get("sort-by", '')
		category = request.GET.get("category", '')
		photos = None
		# ignore case-sensitivity
		words = re.split(r"[^A-Za-z']+", query_string)
		# send query
		query = Q()
		# analyze the search results
		for word in words:
    		# 'or' the queries together
   			query |= Q(description__icontains=word) | Q(tags__icontains=word)

		# check how the photos are sorted, by likes or time
		if sorted_by == 'likes':
			photos = Photo.objects.filter(query).annotate(q_count=Count('likes')).order_by('-q_count')
		elif sorted_by == 'latest':
			photos = Photo.objects.filter(query).order_by('-date_added')
		else:
			photos = Photo.objects.filter(query)
			
		if category != 'all':
			photos = photos.filter(categories=category)
		
		ctx = {
			'photos': photos,
			'query': query_string,
			'sorted_by': sorted_by,
			'category_searched': category
		}
		# show the search results
		return render(request, 'explore_scotland_app/search-photos.html', ctx)

# get the photo details
def picture_details(request, photo_id):
	# check first if the photo exists
	try:
		photo = Photo.objects.get(pk=photo_id)
	except Photo.DoesNotExist:

explore_scotland_app/templates/explore_scotland_app/base.html
<!DOCTYPEhtml>
{% load static %}
<html>

<head>
    <title>Explore Scotland - {% block title_block %}{% endblock %} </title>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="shortcut icon" type="image/png" href="{% static 'explore_scotland_app/img/favicon.ico' %}"/>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" type="text/css" href="{% static 'explore_scotland_app/main.css' %}">
</head>

<body>
	<div id="message_modal" class="modal" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-body">
			{% if messages %}
			<ul class="messages">
				{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
				{% endfor %}
			</ul>
			{% endif %}
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		  </div>
		</div>
	  </div>
	</div>
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    	<span class="navbar-toggler-icon"></span>
  	  </button>
	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav ml-auto mr-5 pr-5">
		  {% if user.is_authenticated %}
		  <li class="nav-item active">
			<span class="nav-link"><span class="d-flex">
				<a href="{% url 'explore_scotland_app:index' %}" class="btn btn-sm btn-outline-light">Home</a>
			</span>
		  </li>
		  <li class="nav-item">
			<span class="nav-link"><span class="d-flex">
				<a class="btn btn-sm btn-outline-light" href="{% url 'explore_scotland_app:upload_photo' %}">Upload Photo</a>
			</span>
		  </li>
		  <li class="nav-item dropdown">
			<span class="nav-link" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
				<a class="dropdown-toggle btn btn-sm btn-outline-light" href="#">
				 Account
				</a>
			</span>
			<div class="dropdown-menu" aria-labelledby="navbarDropdown">
			  <a class="dropdown-item" href="{% url 'explore_scotland_app:profile' %}">Dashboard</a>
			  <a class="dropdown-item" href="{% url 'explore_scotland_app:edit_profile' %}">Edit account</a>
			  <div class="dropdown-divider"></div>
			  <a class="dropdown-item" href="{% url 'explore_scotland_app:logout' %}">Logout</a>
			</div>
		  </li>
		  <li class="nav-item">
			<span class="nav-link disabled">
				<span class="d-flex align-items-center text-light">
					<div class="rounded-circle profile-circle overflow-hidden border border-dark d-flex align-items-center mr-3">
						{% if request.user.profile.picture %}
						<img class="img-fluid" src="{{MEDIA_ROOT}}{{request.user.profile.picture.url}}">
						{% endif %}
					</div> Hello {{request.user}}
				</span>
			</span>
		  </li>
		  {% else %}
		  <li class="nav-item">
			<span class="nav-link"><span class="d-flex">
				<a href="{% url 'explore_scotland_app:login' %}" class="btn btn-sm btn-outline-light">Login / Signup</a>
			</span>
		  </li>
		  {% endif %}
		</ul>
	  </div>
	</nav>
	<div class="container">
		<div class="text-center">
			<a href="{% url 'explore_scotland_app:index' %}"><img src="{% static 'explore_scotland_app/logo/logo.png' %}" width="150" height="150"  alt="Logo"/></a>
		</div>
		{% block body_block %} {% endblock %}
		<footer class="d-flex justify-content-around align-items-center flex-wrap mt-5 pb-3">
			<span>Copyright © 2020 Team F. All web design rights reserved.</span>
			<a id="daily-board" href="{% url 'explore_scotland_app:photo_board' 'daily-board' %}">Daily Board</a>
			<a id="weekly-board" href="{% url 'explore_scotland_app:photo_board' 'weekly-board' %}">Weekly Board </a>
			<a id="monthly-board" href="{% url 'explore_scotland_app:photo_board' 'monthly-board' %}">Monthly Board </a>
			<a id="overall-board" href="{% url 'explore_scotland_app:photo_board' 'overall-board' %}">Overall Board </a>
			<a id="about" href="{% url 'explore_scotland_app:about' %}">About Us</a>
		</footer>
	</div>
	
	<script src="{% static 'explore_scotland_app/main.js' %}"></script>
	
	
	<!-- some inline scripts are used because we found it more efficient loading the js code
	on only necessary pages, and not on every page -->	
	{% block script_block %} {% endblock %}
	
</body>

</html>

explore_scotland_app/templates/explore_scotland_app/edit-profile.html
{% extends './base.html' %}
{% load static %}

{% block title_block %} Edit Profile {% endblock %}

{% block body_block %}
	<h1>Edit Profile</h1>
	<strong>Edit your account details here!</strong> <br/>
	<div class="row">
		<div class="col-md-6 border bg-light p-5">
			<form id="user_form" method="post" action="{% url 'explore_scotland_app:edit_profile' %}" enctype="multipart/form-data">
				{% csrf_token %}
				<!-- Display each form -->
				{{ user_form.as_p }}
				{{ profile_form.as_p }}
				<!-- Provide a button to click to submit the form. -->
				<input type="submit" name="submit" value="Update" />
			</form>
		</div>
		<div class="col-md-6 d-flex align-items-center justify-content-center bg-dark p-5">
			<a id="delete_account_btn" href="{% url 'explore_scotland_app:delete_user' %}" class="btn btn-danger btn-lg" onclick="return confirm_delete()">Delete account</a>
		</div>
	</div>
{% endblock %}

explore_scotland_app/templates/explore_scotland_app/photo-board.html
  {% extends './base.html' %}
{% load static %}
{% load explore_scotland_tags %}

{% block title_block %}Photo Board{% endblock %}

{% block body_block %}

<div class="photo-board">
	<h4>Photos For You</h4>

	{% photo_carousel %}
	
</div>
{% endblock %}

{% block script_block %}
<script>

doAjaxImage(
	`{% if board_type == 'daily-board' %}
		{% url 'explore_scotland_app:get_photos_from_days_ago' 0 %}
	{% elif board_type == 'weekly-board' %}
		{% url 'explore_scotland_app:get_photos_from_days_ago' 7 %}
	{% elif board_type == 'monthly-board' %}
		{% url 'explore_scotland_app:get_photos_from_days_ago' 30 %}
	{% elif board_type == 'overall-board' %}
		{% url 'explore_scotland_app:get_all_photos' 10 %}
	{% endif %}`,
	`{% url 'explore_scotland_app:picture_details_without_key' %}`,
	`{{MEDIA_URL}}`,
	`{{board_type}}`
);

</script>
{% endblock %}

explore_scotland_app/templates/explore_scotland_app/picture-details.html
{% extends './base.html' %}
{% load static %}

{% block title_block %} Picture {% endblock %}

{% block body_block %}
	<div>
		<div class="d-flex align-items-center border-top py-3">
			<div class="rounded-circle profile-circle overflow-hidden border border-dark d-flex align-items-center">
				{% if photo.owner.picture %}
				<img class="img-fluid" src="{{MEDIA_ROOT}}{{photo.owner.picture.url}}">
				{% endif %}
			</div>
			<span><strong class="ml-3">{{photo.owner}}</strong> posted on {{photo.date_added}}</span>
		</div>
		
		<div class="border-top py-3">
			<div class="">
				<iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&layout=button_count&size=small&width=96&height=20&appId" width="96" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
				<a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
			</div>
			<div class="photo-container-big">
				<img class="border rounded mw-100" src={{photo.picture.url}}>
			</div>
		
			<span class="badge">{{photo.likes.all.count}} likes</span>
		
			<div class="mt-3">
				<a class="btn btn-primary btn-sm" href="{% url 'explore_scotland_app:like_photo' photo_id=photo.pk %}">{% if request.user.profile in photo.likes.all %}Dislike{% else %}Like{% endif %}</a>
		
				{% if photo.owner == request.user.profile %}
				<a class="btn btn-primary btn-sm" href="{% url 'explore_scotland_app:edit_photo' photo_id=photo.pk %}">Edit</a>
				<a class="btn btn-danger btn-sm" href="{% url 'explore_scotland_app:delete_photo' photo_id=photo.pk %}" onclick="return confirm_delete()">Delete</a>
				{% endif %}
			</div>
		</div>
		
		<div class="border-top py-3">
			<p>
				{{photo.description}}
			</p>
			<span id="tags" class="mt-3">
				<small class='badge badge-primary mr-1'>{{photo.get_categories_display}}</small>
			</span>
		</div>
	</div>
		
	<div id="comment-form" class="border-top py-3">
		<h4>Post comment</h4>
		<span id="comment_help" class="hide-this">
		</span>
		<form id="comment_form" method="post" action="{% url 'explore_scotland_app:post_comment' photo_id=photo.id %}" class="mt-3">
			{% csrf_token %}
			<!-- Display each form -->
			{{ comment_form.as_p }}
			<input type="hidden" name="photo_id" value={{photo.id}}>
			<input type="hidden" name="comment_id">
			<!-- Provide a button to click to submit the form. -->
			<input type="submit" name="submit" value="Post"/>
		</form>
	</div>
	
	<div>
		<h4>Other comments</h4>
		{% if not comments %}
			<p class="text-center">No comments</p>
		{% endif %}
		{% for comment in comments %}
		<div class="card mt-3">
		  <div class="card-body">
			<h5 class="card-title">{{comment.owner}}</h5>
			<h6 class="card-subtitle mb-2 text-muted">{{comment.date_added}}</h6>
			<p class="card-text">{{comment.content}}</p>
			<a id="reply" class="card-link" href="#comment-form" onclick="commentComment({{comment.id}}, '{{comment.owner}}')">Reply</a>
		  </div>
		</div>
		<div class="ml-5">
			{% for comment in comment.comment_comments.all %}
			<div class="card mt-3">
			  <div class="card-body">
				<h5 class="card-title">{{comment.owner}}</h5>
				<h6 class="card-subtitle mb-2 text-muted">{{comment.date_added}}</h6>
				<p class="card-text">{{comment.content}}</p>
			  </div>
			</div>
			{% endfor %}
		</div>
		{% endfor %}
	</div>
{% endblock %}

{% block script_block %}
<script>
	loadTags("{{photo.tags}}");
</script>
{% endblock %}